import { StyleSheet } from "react-native";

const PRIMARY = "#00AA5D";
const ACCENT = "#ffffff";
const SURFACE = "#F3FFFA";
const BORDER = "#D4F2E3";
const SHADOW = "#082E1C";

export { ACCENT, PRIMARY };

export const doctorRegistrationStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: PRIMARY,
  },
  heroAccent: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 280,
    backgroundColor: PRIMARY,
    zIndex: -1,
  },
  heroCard: {
    backgroundColor: PRIMARY,
    borderRadius: 28,
    padding: 22,
    shadowColor: SHADOW,
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 18 },
    shadowRadius: 32,
    elevation: 10,
  },
  heroPattern: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    height: 280,
    opacity: 0.1,
  },
  container: {
    flex: 1,
    paddingTop: 40,
  },
  header: {
    paddingHorizontal: 24,
    paddingBottom: 24,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: ACCENT,
    marginBottom: 8,
  },
  headerSubtitle: {
    fontSize: 16,
    color: ACCENT,
    opacity: 0.8,
  },
  content: {
    flex: 1,
    backgroundColor: SURFACE,
    borderTopLeftRadius: 24,
    borderTopRightRadius: 24,
    paddingHorizontal: 24,
    paddingTop: 32,
  },
  uploadSection: {
    backgroundColor: ACCENT,
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: BORDER,
  },
  uploadSectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  dropZone: {
    borderWidth: 2,
    borderColor: BORDER,
    borderStyle: "dashed",
    borderRadius: 12,
    padding: 24,
    alignItems: "center",
    backgroundColor: SURFACE,
  },
  dropZoneText: {
    fontSize: 14,
    color: "#7CA28F",
    marginTop: 8,
    textAlign: "center",
  },
  card: {
    backgroundColor: ACCENT,
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: BORDER,
  },
  shadowed: {
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 8,
    elevation: 4,
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#173326",
    marginBottom: 4,
  },
  cardSubtitle: {
    fontSize: 14,
    color: "#666",
    lineHeight: 20,
  },
  linkButton: {
    backgroundColor: PRIMARY,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  linkButtonText: {
    color: ACCENT,
    fontSize: 12,
    fontWeight: "600",
  },
  fieldBlock: {
    marginBottom: 16,
  },
  label: {
    fontSize: 14,
    fontWeight: "600",
    color: "#173326",
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    backgroundColor: ACCENT,
    color: "#173326",
  },
  textArea: {
    height: 100,
    textAlignVertical: "top",
  },
  dateInput: {
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: ACCENT,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  dateValue: {
    fontSize: 14,
    color: "#173326",
  },
  datePlaceholder: {
    fontSize: 14,
    color: "#999",
  },
  selectBox: {
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    backgroundColor: ACCENT,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  selectPlaceholder: {
    fontSize: 14,
    color: "#999",
  },
  selectValue: {
    fontSize: 14,
    color: "#173326",
  },
  dropdownFloat: {
    position: "absolute",
    top: "100%",
    left: 0,
    right: 0,
    backgroundColor: ACCENT,
    borderWidth: 1,
    borderColor: BORDER,
    borderTopWidth: 0,
    borderTopLeftRadius: 0,
    borderTopRightRadius: 0,
    borderBottomLeftRadius: 8,
    borderBottomRightRadius: 8,
    zIndex: 1000,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  primaryButton: {
    backgroundColor: PRIMARY,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    paddingHorizontal: 20,
    borderRadius: 12,
    marginBottom: 16,
  },
  primaryButtonText: {
    color: ACCENT,
    fontSize: 16,
    fontWeight: "600",
    marginLeft: 8,
  },
  entryCard: {
    backgroundColor: "#FFFFFF",
    borderRadius: 12,
    padding: 16,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: BORDER,
  },
  entryHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  badge: {
    backgroundColor: "#E8F5E8",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
  },
  badgeText: {
    fontSize: 12,
    color: "#4CAF50",
    fontWeight: "600",
  },
  sectionHint: {
    fontSize: 12,
    color: "#7CA28F",
    marginBottom: 8,
    fontStyle: "italic",
  },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 16,
  },
  checkbox: {
    width: 20,
    height: 20,
    borderWidth: 2,
    borderColor: BORDER,
    borderRadius: 4,
    marginRight: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  checkboxChecked: {
    backgroundColor: PRIMARY,
    borderColor: PRIMARY,
  },
  checkboxLabel: {
    fontSize: 14,
    color: "#173326",
  },
  actionRow: {
    flexDirection: "row",
    gap: 12,
    paddingHorizontal: 24,
    paddingBottom: 32,
  },
  secondaryButton: {
    flex: 1,
    backgroundColor: ACCENT,
    borderWidth: 1,
    borderColor: PRIMARY,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  secondaryText: {
    color: PRIMARY,
    fontSize: 16,
    fontWeight: "600",
  },
  ctaButton: {
    flex: 2,
    backgroundColor: PRIMARY,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
  },
  ctaText: {
    color: ACCENT,
    fontSize: 16,
    fontWeight: "700",
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  modalContent: {
    backgroundColor: ACCENT,
    borderRadius: 16,
    padding: 24,
    width: "100%",
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#173326",
    marginBottom: 8,
    textAlign: "center",
  },
  modalSubtitle: {
    fontSize: 14,
    color: "#666",
    textAlign: "center",
    marginBottom: 20,
  },
  scanButton: {
    backgroundColor: PRIMARY,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
    marginBottom: 12,
  },
  scanButtonText: {
    color: ACCENT,
    fontSize: 14,
    fontWeight: "600",
  },
  cancelButton: {
    borderWidth: 1,
    borderColor: BORDER,
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  cancelButtonText: {
    color: "#666",
    fontSize: 14,
    fontWeight: "600",
  },
  progressContainer: {
    alignItems: "center",
    paddingVertical: 20,
  },
  progressCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    borderWidth: 4,
    borderColor: BORDER,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 12,
  },
  progressText: {
    fontSize: 18,
    fontWeight: "700",
    color: PRIMARY,
  },
  progressLabel: {
    fontSize: 14,
    color: "#666",
    marginBottom: 20,
  },
  reviewContainer: {
    alignItems: "center",
    paddingVertical: 20,
  },
  reviewActions: {
    flexDirection: "row",
    gap: 12,
  },
  reviewButton: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: "center",
  },
  retakeButton: {
    backgroundColor: ACCENT,
    borderWidth: 1,
    borderColor: BORDER,
  },
  deleteButton: {
    padding: 4,
  },
  saveButton: {
    backgroundColor: PRIMARY,
  },
  buttonText: {
    fontSize: 14,
    fontWeight: "600",
  },
  retakeText: {
    color: "#666",
  },
  deleteText: {
    color: ACCENT,
  },
  saveText: {
    color: ACCENT,
  },
  docType: {
    color: "#173326",
    fontWeight: "600",
    fontSize: 14,
  },
  docHint: {
    color: "#7CA28F",
    fontSize: 12,
    marginTop: 2,
  },
  uploadButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: PRIMARY,
    borderRadius: 8,
    backgroundColor: "rgba(0, 170, 93, 0.05)",
  },
  uploadButtonText: {
    color: PRIMARY,
    fontWeight: "600",
    fontSize: 12,
  },
  // Additional styles for doctor registration
  scrollContent: {
    paddingTop: 0,
    paddingHorizontal: 0,
    paddingBottom: 40,
  },
  sheet: {
    marginTop: 16,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    backgroundColor: SURFACE,
    paddingHorizontal: 20,
    paddingTop: 28,
    paddingBottom: 60,
    gap: 18,
  },
  backRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 12,
  },
  backText: {
    color: ACCENT,
    fontWeight: "600",
  },
  title: {
    fontSize: 24,
    fontWeight: "800",
    color: ACCENT,
  },
  subtitle: {
    marginTop: 4,
    color: "#E2FFEF",
  },
  infoCard: {
    flexDirection: "row",
    padding: 18,
    borderRadius: 22,
    backgroundColor: ACCENT,
    borderWidth: 1,
    borderColor: BORDER,
    gap: 16,
  },
  infoAvatar: {
    width: 60,
    height: 60,
    borderRadius: 16,
    backgroundColor: "#E0F7EE",
    alignItems: "center",
    justifyContent: "center",
  },
  infoTitle: {
    fontWeight: "600",
    color: "#0F3824",
    marginBottom: 4,
  },
  infoHighlight: {
    color: PRIMARY,
    fontWeight: "700",
    marginBottom: 8,
  },
  infoMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 4,
  },
  infoMetaText: {
    color: "#4D5E56",
  },
  dualCard: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    padding: 18,
    borderRadius: 22,
    backgroundColor: ACCENT,
    borderColor: BORDER,
    borderWidth: 1,
  },
  dualTitle: {
    fontWeight: "700",
    color: "#0F3824",
  },
  dualSubtitle: {
    color: "#4D5E56",
    marginTop: 4,
  },
  dualButton: {
    backgroundColor: PRIMARY,
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 999,
  },
  dualButtonText: {
    color: ACCENT,
    fontWeight: "600",
  },
  addDocButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 10,
    backgroundColor: "#F8FFFC",
    alignSelf: "flex-start",
  },
  addDocButtonDisabled: {
    opacity: 0.5,
    backgroundColor: "#F8FFFC",
  },
  addDocButtonText: {
    color: PRIMARY,
    fontWeight: "600",
    fontSize: 14,
  },
  docList: {
    gap: 8,
  },
  docRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 10,
    backgroundColor: "#FBFFFD",
  },
  scanOverlay: {
    flex: 1,
    backgroundColor: "rgba(0,0,0,0.35)",
    justifyContent: "center",
    padding: 20,
  },
  scanCard: {
    backgroundColor: ACCENT,
    borderRadius: 24,
    padding: 20,
    gap: 18,
  },
  scanHeader: {
    gap: 6,
  },
  scanTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0F2D1C",
  },
  scanSubtitle: {
    color: "#4A5F55",
  },
  previewBox: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#C5EED3",
    padding: 24,
    backgroundColor: "#EFFFF4",
  },
  scanStatus: {
    fontWeight: "700",
    color: "#0F3824",
    fontSize: 16,
  },
  scanHint: {
    color: "#4A5F55",
    textAlign: "center",
  },
  progressTrack: {
    width: "100%",
    height: 6,
    borderRadius: 999,
    backgroundColor: "#CBEFD8",
  },
  progressBar: {
    height: 6,
    borderRadius: 999,
    backgroundColor: PRIMARY,
  },
  instructionsBox: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: "#E1F5E8",
    backgroundColor: "#F8FFFB",
    padding: 16,
    gap: 10,
  },
  instructionsTitle: {
    fontWeight: "700",
    color: "#0F3824",
  },
  instructionRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  instructionsText: {
    color: "#42554C",
  },
  scanButtonRow: {
    flexDirection: "row",
    justifyContent: "flex-end",
    gap: 12,
  },
  ghostButton: {
    paddingHorizontal: 18,
    paddingVertical: 12,
    borderRadius: 999,
    borderWidth: 1,
    borderColor: BORDER,
  },
  ghostButtonText: {
    color: "#0F3824",
    fontWeight: "600",
  },
  primaryButtonFilled: {
    paddingHorizontal: 22,
    paddingVertical: 12,
    borderRadius: 999,
    backgroundColor: PRIMARY,
  },
  primaryButtonFilledText: {
    color: ACCENT,
    fontWeight: "700",
  },
});
