import { StyleSheet } from "react-native";

export const PRIMARY = "#00AA5D";
export const ACCENT = "#ffffff";
export const CANVAS = "#D9FFF1";
export const CARD = "#F7FFFC";
export const BORDER = "#B8F2D6";
export const SHADOW = "#082F1B";

export const serviceProviderRegistrationStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: PRIMARY,
  },
  scrollContent: {
    paddingTop: 0,
    paddingBottom: 48,
  },
  sheet: {
    marginTop: 18,
    borderTopLeftRadius: 36,
    borderTopRightRadius: 36,
    backgroundColor: CANVAS,
    paddingHorizontal: 20,
    paddingVertical: 28,
    gap: 18,
  },
  heroCard: {
    backgroundColor: PRIMARY,
    borderRadius: 28,
    padding: 22,
    shadowColor: SHADOW,
    shadowOpacity: 0.2,
    shadowOffset: { width: 0, height: 18 },
    shadowRadius: 32,
    elevation: 10,
  },
  backRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    marginBottom: 12,
  },
  backText: {
    color: ACCENT,
    fontWeight: "600",
  },
  title: {
    fontSize: 24,
    fontWeight: "800",
    color: ACCENT,
  },
  subtitle: {
    marginTop: 4,
    color: "#E2FFEF",
  },
  infoCard: {
    flexDirection: "row",
    padding: 18,
    borderRadius: 24,
    backgroundColor: CARD,
    borderWidth: 1,
    borderColor: BORDER,
    gap: 16,
  },
  infoAvatar: {
    width: 58,
    height: 58,
    borderRadius: 18,
    backgroundColor: "#EFFFF6",
    alignItems: "center",
    justifyContent: "center",
  },
  infoTitle: {
    fontWeight: "600",
    color: "#0F3824",
  },
  infoHighlight: {
    color: PRIMARY,
    fontWeight: "700",
    marginVertical: 6,
  },
  infoMetaRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  infoMeta: {
    color: "#385746",
  },
  card: {
    backgroundColor: CARD,
    borderRadius: 24,
    padding: 18,
    borderWidth: 1,
    borderColor: BORDER,
  },
  shadowed: {
    shadowColor: SHADOW,
    shadowOpacity: 0.08,
    shadowOffset: { width: 0, height: 10 },
    shadowRadius: 18,
    elevation: 6,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: "700",
    color: "#0F3824",
  },
  cardSubtitle: {
    color: "#496757",
    marginTop: 4,
    lineHeight: 20,
  },
  dropZone: {
    marginTop: 16,
    borderWidth: 1,
    borderStyle: "dashed",
    borderColor: PRIMARY,
    borderRadius: 18,
    padding: 26,
    alignItems: "center",
    gap: 8,
    backgroundColor: "#F0FFF8",
  },
  dropZoneText: {
    color: PRIMARY,
    fontWeight: "600",
  },
  sectionHint: {
    fontSize: 12,
    color: "#7C8A83",
    marginTop: 4,
    marginBottom: 8,
  },
  selectedCompaniesList: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  selectedCompanyItem: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#E8F5EE",
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 20,
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 6,
  },
  selectedCompanyText: {
    color: "#1F4F38",
    fontSize: 14,
    fontWeight: "600",
  },
  removeCompanyButton: {
    padding: 2,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "flex-start",
    gap: 12,
  },
  sectionContent: {
    marginTop: 16,
    gap: 14,
  },
  fieldBlock: {
    gap: 6,
  },
  label: {
    color: "#1E4D35",
    fontWeight: "600",
  },
  input: {
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 12,
    fontSize: 15,
    color: "#0F3824",
    backgroundColor: ACCENT,
  },
  textArea: {
    height: 110,
  },
  selectBox: {
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 18,
    paddingHorizontal: 16,
    paddingVertical: 12,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: ACCENT,
  },
  selectPlaceholder: {
    color: "#648778",
  },
  selectValue: {
    color: "#0F3824",
    fontWeight: "600",
  },
  dropdownPanel: {
    position: "absolute",
    top: 60,
    left: 0,
    right: 0,
    backgroundColor: ACCENT,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: BORDER,
    shadowColor: SHADOW,
    shadowOpacity: 0.12,
    shadowOffset: { width: 0, height: 12 },
    shadowRadius: 20,
    elevation: 10,
    zIndex: 40,
  },
  dropdownOption: {
    paddingVertical: 12,
    paddingHorizontal: 16,
  },
  dropdownText: {
    color: "#173326",
    fontSize: 15,
  },
  badge: {
    alignSelf: "flex-start",
    borderRadius: 999,
    paddingHorizontal: 16,
    paddingVertical: 6,
    backgroundColor: "#E6FFF4",
  },
  badgeText: {
    color: PRIMARY,
    fontWeight: "600",
  },
  chipWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 8,
    marginTop: 8,
  },
  facilityChip: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    backgroundColor: PRIMARY,
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  facilityChipText: {
    color: ACCENT,
    fontWeight: "600",
  },
  facilityInputRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  addButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    backgroundColor: PRIMARY,
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 10,
  },
  addButtonText: {
    color: ACCENT,
    fontWeight: "600",
  },
  actionRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 14,
    marginTop: 4,
  },
  secondaryButton: {
    flex: 1,
    borderWidth: 1,
    borderColor: PRIMARY,
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: "center",
    backgroundColor: ACCENT,
  },
  secondaryText: {
    color: PRIMARY,
    fontWeight: "700",
  },
  ctaButton: {
    flex: 1,
    backgroundColor: PRIMARY,
    borderRadius: 18,
    paddingVertical: 14,
    alignItems: "center",
  },
  ctaText: {
    color: ACCENT,
    fontWeight: "700",
  },
  linkButton: {
    borderWidth: 1,
    borderColor: PRIMARY,
    borderRadius: 999,
    paddingHorizontal: 14,
    paddingVertical: 6,
  },
  linkButtonText: {
    color: PRIMARY,
    fontWeight: "600",
  },
  entryCard: {
    padding: 16,
    borderWidth: 1,
    borderColor: BORDER,
    borderRadius: 16,
    backgroundColor: "#FBFFFD",
    gap: 12,
  },
  entryHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  deleteButton: {
    padding: 4,
  },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
  },
  checkboxBox: {
    width: 18,
    height: 18,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: BORDER,
    backgroundColor: "#FBFFFD",
  },
  checkboxChecked: {
    backgroundColor: PRIMARY,
    borderColor: PRIMARY,
  },
  checkboxLabel: {
    color: "#2D3F35",
  },
  documentUploadContainer: {
    marginBottom: 20,
  },
  documentLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#2D3F35",
    marginBottom: 8,
  },
  uploadButton: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#F8F9FA",
    borderWidth: 2,
    borderColor: "#E0E0E0",
    borderStyle: "dashed",
    borderRadius: 12,
    padding: 20,
    gap: 12,
  },
  uploadButtonText: {
    fontSize: 14,
    fontWeight: "500",
    color: "#2D3F35",
  },
  uploadHint: {
    fontSize: 12,
    color: "#666",
    textAlign: "center",
    marginTop: 8,
  },
});
